//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000 - Egg
        ///001 - Bulbasaur
        ///002 - Ivysaur
        ///003 - Venusaur
        ///004 - Charmander
        ///005 - Charmeleon
        ///006 - Charizard
        ///007 - Squirtle
        ///008 - Wartortle
        ///009 - Blastoise
        ///010 - Caterpie
        ///011 - Metapod
        ///012 - Butterfree
        ///013 - Weedle
        ///014 - Kakuna
        ///015 - Beedrill
        ///016 - Pidgey
        ///017 - Pidgeotto
        ///018 - Pidgeot
        ///019 - Rattata
        ///020 - Raticate
        ///021 - Spearow
        ///022 - Fearow
        ///023 - Ekans
        ///024 - Arbok
        ///025 - Pikachu
        ///026 - Raichu
        ///027 - Sandshrew
        ///028 - Sandslash
        ///029 - Nidoran♀
        ///030 - Nidorina
        ///031 - Nidoqueen
        ///032 - Nidoran♂
        ///033 - Nidorino
        ///034 - Nidoking
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mons {
            get {
                return ResourceManager.GetString("mons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 000 - Egg
        ///001 - Bulbasaur
        ///002 - Ivysaur
        ///003 - Venusaur
        ///004 - Charmander
        ///005 - Charmeleon
        ///006 - Charizard
        ///007 - Squirtle
        ///008 - Wartortle
        ///009 - Blastoise
        ///010 - Caterpie
        ///011 - Metapod
        ///012 - Butterfree
        ///013 - Weedle
        ///014 - Kakuna
        ///015 - Beedrill
        ///016 - Pidgey
        ///017 - Pidgeotto
        ///018 - Pidgeot
        ///019 - Rattata
        ///020 - Raticate
        ///021 - Spearow
        ///022 - Fearow
        ///023 - Ekans
        ///024 - Arbok
        ///025 - Pikachu
        ///026 - Raichu
        ///027 - Sandshrew
        ///028 - Sandslash
        ///029 - Nidoran♀
        ///030 - Nidorina
        ///031 - Nidoqueen
        ///032 - Nidoran♂
        ///033 - Nidorino
        ///034 - Nidoking
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mons2 {
            get {
                return ResourceManager.GetString("mons2", resourceCulture);
            }
        }
    }
}
